### ISSUE TITLE
404 when retrieving current game information

### ISSUE THREAD

**Issue by pneubeck** [aj-r/RiotNet#1]
Hey there,
first of all i want to thank you for your work. I really appreciate it. 
The issue i have occurs when I am trying to get the current Game Information. like
"client.GetCurrentGameBySummonerId(_currentSummoner.Id)". I get an error 404. Did Riot change the URLs used for these request and you havent implemented it yet ? Or am I missing something ? 
Thanks in advance

**Comment by aj-r** [comment]
Hmmm... I'll look into it.

**Comment by aj-r** [comment]
Hey, I looked into it, and my tests for GetCurrentGameBySummonerId are
still passing, so I don't think the URL changed.

My advice would be to check that your summoner ID is correct. If you pass
in a summoner ID that does not exist, the API will give you a 404 error.

It could also be that the API is derping out. I've had issues in the past
where it just gives me intermittent errors for no reason because their
servers are having issues. Also usually it gave me a 500 or 429 error code,
not 404.

If you are sure the summoner ID is correct, let me know and I'll look into
it further. Happy coding!

**Comment by pneubeck** [comment]
Good lord...
I am having a very bad thought. I am sure the ID is correct. But it came to my mind that I possibly got the 404 error because i was trying to get information on a custon game (which i created for testing purposes). I will try if it works in normals this evening. Should this be the case I will ofcourse report back to you. And shame shall be on me... like a lot.
Thanks for your answers. Ill be in touch

**Comment by aj-r** [comment]
Ah... that would do it. I don't think the API works on custom games
(although I think they are adding a thing so you can make a tournament and
get data from that).

**Comment by pneubeck** [comment]
Yes. this is it. Just tried it with a friend who was ingame. I am soooo sorry I bothered you with this. 
I was just not thinking far enough when testing. Totally my bad. 
Thanks for your help anyway. And great job on the api!
I guess this "issue" can be closed ;)
